# Generated by Django 5.1.2 on 2024-10-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YeelighBulb",
            new_name="YeelightBulb",
        ),
    ]
