# Generated by Django 5.1.2 on 2024-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0002_rename_yeelighbulb_yeelightbulb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yeelightbulb",
            name="bulb_id",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="yeelightbulb",
            name="ip",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="yeelightbulb",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
