# Generated by Django 5.1.2 on 2024-10-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0003_alter_yeelightbulb_bulb_id_alter_yeelightbulb_ip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
                ("r", models.IntegerField(max_length=3)),
                ("g", models.IntegerField(max_length=3)),
                ("b", models.IntegerField(max_length=3)),
                ("brightness", models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
                ("kelvins", models.IntegerField(max_length=4)),
                ("brightness", models.IntegerField(max_length=3)),
            ],
        ),
    ]
