# Generated by Django 5.1.2 on 2024-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0004_color_temperature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="color",
            name="b",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="color",
            name="brightness",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="color",
            name="g",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="color",
            name="r",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="temperature",
            name="brightness",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="temperature",
            name="kelvins",
            field=models.IntegerField(),
        ),
    ]
