# Generated by Django 5.1.2 on 2024-10-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0005_timer_alter_color_b_alter_color_brightness_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("action", models.CharField(max_length=32)),
                ("device", models.CharField(max_length=32)),
                ("preset", models.CharField(max_length=32)),
            ],
        ),
    ]
