# Generated by Django 5.1.2 on 2024-10-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0006_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="action",
            field=models.CharField(
                choices=[
                    ("on-off", "Power"),
                    ("color", "Color"),
                    ("timer", "Timer"),
                    ("temperature", "Temperature"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="garlight.yeelightbulb"
            ),
        ),
    ]
