# Generated by Django 5.1.2 on 2024-10-18 18:05

import garlight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0007_alter_endpoint_action_alter_endpoint_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brightness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
                ("brightness", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="preset",
            field=models.CharField(choices=garlight.models.presets, max_length=16),
        ),
    ]
