# Generated by Django 5.1.2 on 2024-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0008_brightness_alter_endpoint_preset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="name",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="action",
            field=models.CharField(
                choices=[
                    ("on-off", "Power"),
                    ("color", "Color"),
                    ("timer", "Timer"),
                    ("temperature", "Temperature"),
                    ("brightness", "Brightness"),
                ],
                max_length=16,
            ),
        ),
    ]
