# Generated by Django 5.1.2 on 2024-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garlight", "0009_remove_endpoint_name_alter_endpoint_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="name",
            field=models.CharField(default="", max_length=16),
        ),
    ]
