
#https://api.weatherapi.com/v1/current.json?key=6616c24000f64710920183344250201&q=52.20232214086234,20.943791439663237&aqi=yes
eg_current_response = {
    "location": {
        "name": "Piastow",
        "region": "",
        "country": "Poland",
        "lat": 51.2,
        "lon": 22.85,
        "tz_id": "Europe/Warsaw",
        "localtime_epoch": 1735843371,
        "localtime": "2025-01-02 19:42"
    },
    "current": {
        "last_updated_epoch": 1735842600,
        "last_updated": "2025-01-02 19:30",
        "temp_c": 1.0,
        "temp_f": 33.8,
        "is_day": 0,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 13.0,
        "wind_kph": 20.9,
        "wind_degree": 282,
        "wind_dir": "WNW",
        "pressure_mb": 1007.0,
        "pressure_in": 29.74,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 75,
        "cloud": 25,
        "feelslike_c": -4.1,
        "feelslike_f": 24.6,
        "windchill_c": -1.7,
        "windchill_f": 28.9,
        "heatindex_c": 2.9,
        "heatindex_f": 37.2,
        "dewpoint_c": -3.9,
        "dewpoint_f": 24.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 0.0,
        "gust_mph": 19.0,
        "gust_kph": 30.6,
        "air_quality": {
            "co": 456.95,
            "no2": 27.565,
            "o3": 52.0,
            "so2": 9.065,
            "pm2_5": 26.825,
            "pm10": 28.86,
            "us-epa-index": 2,
            "gb-defra-index": 3
        }
    }
}

# https://api.weatherapi.com/v1/forecast.json?key=6616c24000f64710920183344250201&q=52.20232214086234,20.943791439663237&days=1&aqi=yes&alerts=no
eg_forecast_response = {
    "location": {
        "name": "Piastow",
        "region": "",
        "country": "Poland",
        "lat": 52.2,
        "lon": 20.85,
        "tz_id": "Europe/Warsaw",
        "localtime_epoch": 1735841327,
        "localtime": "2025-01-02 19:08"
    },
    "current": {
        "last_updated_epoch": 1735840800,
        "last_updated": "2025-01-02 19:00",
        "temp_c": 0.2,
        "temp_f": 32.4,
        "is_day": 0,
        "condition": {
            "text": "Clear",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 13.0,
        "wind_kph": 20.9,
        "wind_degree": 282,
        "wind_dir": "WNW",
        "pressure_mb": 1007.0,
        "pressure_in": 29.74,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 80,
        "cloud": 0,
        "feelslike_c": -5.1,
        "feelslike_f": 22.8,
        "windchill_c": -1.7,
        "windchill_f": 28.9,
        "heatindex_c": 2.9,
        "heatindex_f": 37.2,
        "dewpoint_c": -3.9,
        "dewpoint_f": 24.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 0.0,
        "gust_mph": 19.0,
        "gust_kph": 30.6,
        "air_quality": {
            "co": 456.95,
            "no2": 27.565,
            "o3": 52.0,
            "so2": 9.065,
            "pm2_5": 26.825,
            "pm10": 28.86,
            "us-epa-index": 2,
            "gb-defra-index": 3
        }
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2025-01-02",
                "date_epoch": 1735776000,
                "day": {
                    "maxtemp_c": 8.9,
                    "maxtemp_f": 47.9,
                    "mintemp_c": 0.1,
                    "mintemp_f": 32.1,
                    "avgtemp_c": 5.4,
                    "avgtemp_f": 41.7,
                    "maxwind_mph": 24.4,
                    "maxwind_kph": 39.2,
                    "totalprecip_mm": 0.65,
                    "totalprecip_in": 0.03,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 9.3,
                    "avgvis_miles": 5.0,
                    "avghumidity": 59,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 98,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 0.0,
                    "air_quality": {
                        "co": 375.994,
                        "no2": 17.811799999999998,
                        "o3": 57.0,
                        "so2": 7.089200000000001,
                        "pm2_5": 20.128,
                        "pm10": 24.2572,
                        "us-epa-index": 2,
                        "gb-defra-index": 2
                    }
                },
                "astro": {
                    "sunrise": "07:46 AM",
                    "sunset": "03:37 PM",
                    "moonrise": "09:49 AM",
                    "moonset": "06:24 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": 5,
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1735772400,
                        "time": "2025-01-02 00:00",
                        "temp_c": 7.4,
                        "temp_f": 45.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 23.9,
                        "wind_kph": 38.5,
                        "wind_degree": 232,
                        "wind_dir": "SW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 42,
                        "cloud": 51,
                        "feelslike_c": 2.6,
                        "feelslike_f": 36.7,
                        "windchill_c": 2.6,
                        "windchill_f": 36.7,
                        "heatindex_c": 7.4,
                        "heatindex_f": 45.3,
                        "dewpoint_c": -4.7,
                        "dewpoint_f": 23.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 38.3,
                        "gust_kph": 61.6,
                        "uv": 0,
                        "air_quality": {
                            "co": 392.2,
                            "no2": 12.765,
                            "o3": 64.0,
                            "so2": 7.03,
                            "pm2_5": 25.9,
                            "pm10": 28.49,
                            "us-epa-index": 2,
                            "gb-defra-index": 3
                        }
                    },
                    {
                        "time_epoch": 1735776000,
                        "time": "2025-01-02 01:00",
                        "temp_c": 7.3,
                        "temp_f": 45.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                            "code": 1006
                        },
                        "wind_mph": 23.7,
                        "wind_kph": 38.2,
                        "wind_degree": 233,
                        "wind_dir": "SW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 43,
                        "cloud": 72,
                        "feelslike_c": 2.4,
                        "feelslike_f": 36.3,
                        "windchill_c": 2.4,
                        "windchill_f": 36.3,
                        "heatindex_c": 7.3,
                        "heatindex_f": 45.1,
                        "dewpoint_c": -4.6,
                        "dewpoint_f": 23.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 37.8,
                        "gust_kph": 60.8,
                        "uv": 0,
                        "air_quality": {
                            "co": 362.6,
                            "no2": 13.135,
                            "o3": 65.0,
                            "so2": 7.215,
                            "pm2_5": 21.46,
                            "pm10": 24.79,
                            "us-epa-index": 2,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735779600,
                        "time": "2025-01-02 02:00",
                        "temp_c": 7.3,
                        "temp_f": 45.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                            "code": 1006
                        },
                        "wind_mph": 23.5,
                        "wind_kph": 37.8,
                        "wind_degree": 233,
                        "wind_dir": "SW",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 43,
                        "cloud": 71,
                        "feelslike_c": 2.5,
                        "feelslike_f": 36.4,
                        "windchill_c": 2.5,
                        "windchill_f": 36.4,
                        "heatindex_c": 7.3,
                        "heatindex_f": 45.1,
                        "dewpoint_c": -4.5,
                        "dewpoint_f": 23.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 37.5,
                        "gust_kph": 60.4,
                        "uv": 0,
                        "air_quality": {
                            "co": 351.5,
                            "no2": 10.73,
                            "o3": 65.0,
                            "so2": 6.105,
                            "pm2_5": 19.055,
                            "pm10": 22.2,
                            "us-epa-index": 2,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735783200,
                        "time": "2025-01-02 03:00",
                        "temp_c": 7.6,
                        "temp_f": 45.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 23.3,
                        "wind_kph": 37.4,
                        "wind_degree": 234,
                        "wind_dir": "SW",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.67,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 42,
                        "cloud": 100,
                        "feelslike_c": 2.9,
                        "feelslike_f": 37.3,
                        "windchill_c": 2.9,
                        "windchill_f": 37.3,
                        "heatindex_c": 7.6,
                        "heatindex_f": 45.7,
                        "dewpoint_c": -4.4,
                        "dewpoint_f": 24.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 37.0,
                        "gust_kph": 59.6,
                        "uv": 0,
                        "air_quality": {
                            "co": 342.25,
                            "no2": 9.435,
                            "o3": 65.0,
                            "so2": 5.18,
                            "pm2_5": 17.02,
                            "pm10": 21.275,
                            "us-epa-index": 2,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735786800,
                        "time": "2025-01-02 04:00",
                        "temp_c": 8.6,
                        "temp_f": 47.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 23.7,
                        "wind_kph": 38.2,
                        "wind_degree": 237,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.63,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 39,
                        "cloud": 96,
                        "feelslike_c": 4.2,
                        "feelslike_f": 39.5,
                        "windchill_c": 4.2,
                        "windchill_f": 39.5,
                        "heatindex_c": 8.6,
                        "heatindex_f": 47.4,
                        "dewpoint_c": -4.5,
                        "dewpoint_f": 24.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 37.3,
                        "gust_kph": 60.0,
                        "uv": 0,
                        "air_quality": {
                            "co": 333.0,
                            "no2": 8.695,
                            "o3": 65.0,
                            "so2": 4.07,
                            "pm2_5": 15.355,
                            "pm10": 19.425,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735790400,
                        "time": "2025-01-02 05:00",
                        "temp_c": 8.9,
                        "temp_f": 48.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 24.2,
                        "wind_kph": 38.9,
                        "wind_degree": 240,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 39,
                        "cloud": 100,
                        "feelslike_c": 4.6,
                        "feelslike_f": 40.3,
                        "windchill_c": 4.6,
                        "windchill_f": 40.3,
                        "heatindex_c": 8.9,
                        "heatindex_f": 48.1,
                        "dewpoint_c": -4.3,
                        "dewpoint_f": 24.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 37.5,
                        "gust_kph": 60.4,
                        "uv": 0,
                        "air_quality": {
                            "co": 323.75,
                            "no2": 7.585,
                            "o3": 65.0,
                            "so2": 3.885,
                            "pm2_5": 13.135,
                            "pm10": 16.28,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735794000,
                        "time": "2025-01-02 06:00",
                        "temp_c": 8.9,
                        "temp_f": 47.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                            "code": 1006
                        },
                        "wind_mph": 23.9,
                        "wind_kph": 38.5,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.61,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 41,
                        "cloud": 77,
                        "feelslike_c": 4.5,
                        "feelslike_f": 40.1,
                        "windchill_c": 4.5,
                        "windchill_f": 40.1,
                        "heatindex_c": 8.9,
                        "heatindex_f": 47.9,
                        "dewpoint_c": -3.7,
                        "dewpoint_f": 25.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 36.4,
                        "gust_kph": 58.5,
                        "uv": 0,
                        "air_quality": {
                            "co": 316.35,
                            "no2": 7.215,
                            "o3": 65.0,
                            "so2": 3.885,
                            "pm2_5": 12.95,
                            "pm10": 16.465,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735797600,
                        "time": "2025-01-02 07:00",
                        "temp_c": 8.0,
                        "temp_f": 46.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 24.2,
                        "wind_kph": 38.9,
                        "wind_degree": 247,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 51,
                        "cloud": 100,
                        "feelslike_c": 3.4,
                        "feelslike_f": 38.0,
                        "windchill_c": 3.4,
                        "windchill_f": 38.0,
                        "heatindex_c": 8.0,
                        "heatindex_f": 46.4,
                        "dewpoint_c": -1.4,
                        "dewpoint_f": 29.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 64,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 35.3,
                        "gust_kph": 56.8,
                        "uv": 0,
                        "air_quality": {
                            "co": 308.95,
                            "no2": 8.325,
                            "o3": 64.0,
                            "so2": 4.07,
                            "pm2_5": 12.765,
                            "pm10": 16.095,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735801200,
                        "time": "2025-01-02 08:00",
                        "temp_c": 7.0,
                        "temp_f": 44.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 24.4,
                        "wind_kph": 39.2,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 66,
                        "cloud": 100,
                        "feelslike_c": 2.0,
                        "feelslike_f": 35.6,
                        "windchill_c": 2.0,
                        "windchill_f": 35.6,
                        "heatindex_c": 7.0,
                        "heatindex_f": 44.6,
                        "dewpoint_c": 1.0,
                        "dewpoint_f": 33.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 77,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 34.9,
                        "gust_kph": 56.2,
                        "uv": 0.0,
                        "air_quality": {
                            "co": 305.25,
                            "no2": 14.245,
                            "o3": 64.0,
                            "so2": 4.81,
                            "pm2_5": 13.69,
                            "pm10": 15.91,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735804800,
                        "time": "2025-01-02 09:00",
                        "temp_c": 6.7,
                        "temp_f": 44.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 24.2,
                        "wind_kph": 38.9,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 69,
                        "cloud": 100,
                        "feelslike_c": 1.7,
                        "feelslike_f": 35.0,
                        "windchill_c": 1.7,
                        "windchill_f": 35.0,
                        "heatindex_c": 6.7,
                        "heatindex_f": 44.1,
                        "dewpoint_c": 1.4,
                        "dewpoint_f": 34.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 34.0,
                        "gust_kph": 54.8,
                        "uv": 0.1,
                        "air_quality": {
                            "co": 308.95,
                            "no2": 16.835,
                            "o3": 63.0,
                            "so2": 5.55,
                            "pm2_5": 13.875,
                            "pm10": 15.355,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735808400,
                        "time": "2025-01-02 10:00",
                        "temp_c": 6.7,
                        "temp_f": 44.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 23.9,
                        "wind_kph": 38.5,
                        "wind_degree": 243,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.05,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 76,
                        "cloud": 100,
                        "feelslike_c": 1.7,
                        "feelslike_f": 35.0,
                        "windchill_c": 1.7,
                        "windchill_f": 35.0,
                        "heatindex_c": 6.7,
                        "heatindex_f": 44.1,
                        "dewpoint_c": 2.7,
                        "dewpoint_f": 36.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 84,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 33.6,
                        "gust_kph": 54.0,
                        "uv": 0.1,
                        "air_quality": {
                            "co": 305.25,
                            "no2": 17.945,
                            "o3": 60.0,
                            "so2": 5.735,
                            "pm2_5": 13.505,
                            "pm10": 16.465,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735812000,
                        "time": "2025-01-02 11:00",
                        "temp_c": 6.3,
                        "temp_f": 43.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 21.7,
                        "wind_kph": 34.9,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.23,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 83,
                        "cloud": 100,
                        "feelslike_c": 1.4,
                        "feelslike_f": 34.5,
                        "windchill_c": 1.4,
                        "windchill_f": 34.5,
                        "heatindex_c": 6.3,
                        "heatindex_f": 43.4,
                        "dewpoint_c": 3.6,
                        "dewpoint_f": 38.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 30.0,
                        "gust_kph": 48.3,
                        "uv": 0.1,
                        "air_quality": {
                            "co": 308.95,
                            "no2": 14.985,
                            "o3": 58.0,
                            "so2": 5.92,
                            "pm2_5": 10.545,
                            "pm10": 14.43,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735815600,
                        "time": "2025-01-02 12:00",
                        "temp_c": 6.4,
                        "temp_f": 43.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 21.3,
                        "wind_kph": 34.2,
                        "wind_degree": 253,
                        "wind_dir": "WSW",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.62,
                        "precip_mm": 0.13,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 80,
                        "cloud": 100,
                        "feelslike_c": 1.6,
                        "feelslike_f": 34.9,
                        "windchill_c": 1.6,
                        "windchill_f": 34.9,
                        "heatindex_c": 6.5,
                        "heatindex_f": 43.6,
                        "dewpoint_c": 3.3,
                        "dewpoint_f": 38.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 30.0,
                        "gust_kph": 48.2,
                        "uv": 0.2,
                        "air_quality": {
                            "co": 308.95,
                            "no2": 13.32,
                            "o3": 59.0,
                            "so2": 5.735,
                            "pm2_5": 9.99,
                            "pm10": 14.985,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735819200,
                        "time": "2025-01-02 13:00",
                        "temp_c": 6.0,
                        "temp_f": 42.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 20.4,
                        "wind_kph": 32.8,
                        "wind_degree": 273,
                        "wind_dir": "W",
                        "pressure_mb": 1003.0,
                        "pressure_in": 29.63,
                        "precip_mm": 0.16,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 80,
                        "cloud": 100,
                        "feelslike_c": 1.2,
                        "feelslike_f": 34.1,
                        "windchill_c": 1.2,
                        "windchill_f": 34.1,
                        "heatindex_c": 6.0,
                        "heatindex_f": 42.9,
                        "dewpoint_c": 2.9,
                        "dewpoint_f": 37.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 27.4,
                        "gust_kph": 44.1,
                        "uv": 0.1,
                        "air_quality": {
                            "co": 308.95,
                            "no2": 12.95,
                            "o3": 59.0,
                            "so2": 5.18,
                            "pm2_5": 7.585,
                            "pm10": 13.32,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735822800,
                        "time": "2025-01-02 14:00",
                        "temp_c": 4.4,
                        "temp_f": 40.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 18.1,
                        "wind_kph": 29.2,
                        "wind_degree": 276,
                        "wind_dir": "W",
                        "pressure_mb": 1004.0,
                        "pressure_in": 29.66,
                        "precip_mm": 0.08,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 64,
                        "cloud": 87,
                        "feelslike_c": -0.6,
                        "feelslike_f": 30.9,
                        "windchill_c": -0.6,
                        "windchill_f": 30.9,
                        "heatindex_c": 4.4,
                        "heatindex_f": 40.0,
                        "dewpoint_c": -1.7,
                        "dewpoint_f": 28.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.7,
                        "gust_kph": 39.7,
                        "uv": 0.1,
                        "air_quality": {
                            "co": 320.05,
                            "no2": 13.135,
                            "o3": 65.0,
                            "so2": 5.55,
                            "pm2_5": 7.215,
                            "pm10": 11.655,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735826400,
                        "time": "2025-01-02 15:00",
                        "temp_c": 4.3,
                        "temp_f": 39.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 17.7,
                        "wind_kph": 28.4,
                        "wind_degree": 279,
                        "wind_dir": "W",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 56,
                        "cloud": 89,
                        "feelslike_c": -0.7,
                        "feelslike_f": 30.7,
                        "windchill_c": -0.7,
                        "windchill_f": 30.7,
                        "heatindex_c": 4.3,
                        "heatindex_f": 39.7,
                        "dewpoint_c": -3.8,
                        "dewpoint_f": 25.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.7,
                        "gust_kph": 39.8,
                        "uv": 0.0,
                        "air_quality": {
                            "co": 323.75,
                            "no2": 16.28,
                            "o3": 65.0,
                            "so2": 5.92,
                            "pm2_5": 7.955,
                            "pm10": 11.285,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735830000,
                        "time": "2025-01-02 16:00",
                        "temp_c": 3.6,
                        "temp_f": 38.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 17.0,
                        "wind_kph": 27.4,
                        "wind_degree": 283,
                        "wind_dir": "WNW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 55,
                        "cloud": 55,
                        "feelslike_c": -1.5,
                        "feelslike_f": 29.2,
                        "windchill_c": -1.5,
                        "windchill_f": 29.2,
                        "heatindex_c": 3.6,
                        "heatindex_f": 38.5,
                        "dewpoint_c": -4.6,
                        "dewpoint_f": 23.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.4,
                        "gust_kph": 39.3,
                        "uv": 0,
                        "air_quality": {
                            "co": 340.4,
                            "no2": 22.385,
                            "o3": 61.0,
                            "so2": 6.105,
                            "pm2_5": 9.25,
                            "pm10": 12.58,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1735833600,
                        "time": "2025-01-02 17:00",
                        "temp_c": 3.2,
                        "temp_f": 37.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 282,
                        "wind_dir": "WNW",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 58,
                        "cloud": 100,
                        "feelslike_c": -1.6,
                        "feelslike_f": 29.2,
                        "windchill_c": -1.6,
                        "windchill_f": 29.2,
                        "heatindex_c": 3.2,
                        "heatindex_f": 37.8,
                        "dewpoint_c": -4.2,
                        "dewpoint_f": 24.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.1,
                        "gust_kph": 33.9,
                        "uv": 0,
                        "air_quality": {
                            "co": 373.7,
                            "no2": 29.045,
                            "o3": 55.0,
                            "so2": 6.66,
                            "pm2_5": 13.135,
                            "pm10": 14.615,
                            "us-epa-index": 1,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735837200,
                        "time": "2025-01-02 18:00",
                        "temp_c": 3.1,
                        "temp_f": 37.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 13.0,
                        "wind_kph": 20.9,
                        "wind_degree": 281,
                        "wind_dir": "WNW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.73,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 60,
                        "cloud": 100,
                        "feelslike_c": -1.4,
                        "feelslike_f": 29.5,
                        "windchill_c": -1.4,
                        "windchill_f": 29.5,
                        "heatindex_c": 3.1,
                        "heatindex_f": 37.7,
                        "dewpoint_c": -3.9,
                        "dewpoint_f": 25.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 18.9,
                        "gust_kph": 30.3,
                        "uv": 0,
                        "air_quality": {
                            "co": 419.95,
                            "no2": 31.45,
                            "o3": 52.0,
                            "so2": 7.4,
                            "pm2_5": 20.35,
                            "pm10": 21.83,
                            "us-epa-index": 2,
                            "gb-defra-index": 2
                        }
                    },
                    {
                        "time_epoch": 1735840800,
                        "time": "2025-01-02 19:00",
                        "temp_c": 0.2,
                        "temp_f": 32.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.0,
                        "wind_kph": 20.9,
                        "wind_degree": 282,
                        "wind_dir": "WNW",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.74,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 80,
                        "cloud": 0,
                        "feelslike_c": -1.7,
                        "feelslike_f": 28.9,
                        "windchill_c": -1.7,
                        "windchill_f": 28.9,
                        "heatindex_c": 2.9,
                        "heatindex_f": 37.2,
                        "dewpoint_c": -3.9,
                        "dewpoint_f": 24.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.0,
                        "gust_kph": 30.6,
                        "uv": 0,
                        "air_quality": {
                            "co": 456.95,
                            "no2": 27.565,
                            "o3": 52.0,
                            "so2": 9.065,
                            "pm2_5": 26.825,
                            "pm10": 28.86,
                            "us-epa-index": 2,
                            "gb-defra-index": 3
                        }
                    },
                    {
                        "time_epoch": 1735844400,
                        "time": "2025-01-02 20:00",
                        "temp_c": 2.4,
                        "temp_f": 36.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 11.6,
                        "wind_kph": 18.7,
                        "wind_degree": 287,
                        "wind_dir": "WNW",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.75,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 63,
                        "cloud": 58,
                        "feelslike_c": -2.0,
                        "feelslike_f": 28.3,
                        "windchill_c": -2.0,
                        "windchill_f": 28.3,
                        "heatindex_c": 2.4,
                        "heatindex_f": 36.3,
                        "dewpoint_c": -4.0,
                        "dewpoint_f": 24.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 17.2,
                        "gust_kph": 27.6,
                        "uv": 0,
                        "air_quality": {
                            "co": 468.05,
                            "no2": 28.12,
                            "o3": 50.0,
                            "so2": 10.545,
                            "pm2_5": 33.3,
                            "pm10": 37.74,
                            "us-epa-index": 2,
                            "gb-defra-index": 3
                        }
                    },
                    {
                        "time_epoch": 1735848000,
                        "time": "2025-01-02 21:00",
                        "temp_c": 1.7,
                        "temp_f": 35.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 290,
                        "wind_dir": "WNW",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.77,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 26,
                        "feelslike_c": -2.7,
                        "feelslike_f": 27.2,
                        "windchill_c": -2.7,
                        "windchill_f": 27.2,
                        "heatindex_c": 1.7,
                        "heatindex_f": 35.1,
                        "dewpoint_c": -3.7,
                        "dewpoint_f": 25.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.1,
                        "gust_kph": 25.8,
                        "uv": 0,
                        "air_quality": {
                            "co": 458.8,
                            "no2": 22.015,
                            "o3": 50.0,
                            "so2": 9.99,
                            "pm2_5": 27.195,
                            "pm10": 33.855,
                            "us-epa-index": 2,
                            "gb-defra-index": 3
                        }
                    },
                    {
                        "time_epoch": 1735851600,
                        "time": "2025-01-02 22:00",
                        "temp_c": 0.9,
                        "temp_f": 33.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 291,
                        "wind_dir": "WNW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 71,
                        "cloud": 0,
                        "feelslike_c": -3.2,
                        "feelslike_f": 26.3,
                        "windchill_c": -3.2,
                        "windchill_f": 26.3,
                        "heatindex_c": 0.9,
                        "heatindex_f": 33.7,
                        "dewpoint_c": -3.8,
                        "dewpoint_f": 25.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.7,
                        "gust_kph": 22.0,
                        "uv": 0,
                        "air_quality": {
                            "co": 477.3,
                            "no2": 25.9,
                            "o3": 48.0,
                            "so2": 13.135,
                            "pm2_5": 32.745,
                            "pm10": 37.555,
                            "us-epa-index": 2,
                            "gb-defra-index": 3
                        }
                    },
                    {
                        "time_epoch": 1735855200,
                        "time": "2025-01-02 23:00",
                        "temp_c": 0.1,
                        "temp_f": 32.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 279,
                        "wind_dir": "W",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 75,
                        "cloud": 0,
                        "feelslike_c": -3.5,
                        "feelslike_f": 25.7,
                        "windchill_c": -3.5,
                        "windchill_f": 25.7,
                        "heatindex_c": 0.1,
                        "heatindex_f": 32.1,
                        "dewpoint_c": -3.8,
                        "dewpoint_f": 25.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.3,
                        "gust_kph": 18.1,
                        "uv": 0,
                        "air_quality": {
                            "co": 505.05,
                            "no2": 24.79,
                            "o3": 43.0,
                            "so2": 14.615,
                            "pm2_5": 46.99,
                            "pm10": 52.17,
                            "us-epa-index": 3,
                            "gb-defra-index": 5
                        }
                    }
                ]
            }
        ]
    }
}