# Generated by Django 5.1.3 on 2025-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='air_quality',
        ),
        migrations.RemoveField(
            model_name='location',
            name='api_key',
        ),
    ]
